---
title: "Markdown Lab"
format: 
  html:
    theme: 
      light: flatly
      dark: darkly
  docx:
    date: Sep 1, 2022
---

## Agenda

-   Today's lab
    -   [Quarto](https://quarto.org/) tour.
        -   Quarto [documentation guide](https://quarto.org/docs/guide/).
        -   [Markdown basics](https://quarto.org/docs/authoring/markdown-basics.html).
        -   [Formatting code block output](https://quarto.org/docs/output-formats/html-code.html).
    -   The [iris dataset](https://rpubs.com/moeransm/intro-iris).

## The iris dataset

We are going to start with the iris demo from [Rpubs.com](https://rpubs.com/moeransm/intro-iris), and then we'll go back and make some upgrades to the formatting.

1. Start by replicating the information and formatting found at <https://rpubs.com/moeransm/intro-iris> (export HTML code). Be sure to leave a note attirubting the original authors. Save your `iris.qmd` file in the `docs/` directory of your course project repo.

2. Now make it so that the user can opt for [dark mode](https://quarto.org/docs/output-formats/html-themes.html#dark-mode).

3. Turn the paragraph starting "The `summary()` function gives summary statistics for any dataset." into at tip using a [callout block](https://quarto.org/docs/authoring/callouts.html).

4. [Fold the code](https://quarto.org/docs/output-formats/html-code.html#folding-code) in the visualization section, such that only the figures are shown by default.

5. Push your `.qmd` file and rendered html to GitHub and enable GitHub pages. Your webpage should now be live! My page will be at <https://johnsonra.github.io/BIFXproject/iris.html>. Replace my username with yours to see your page.

5. Export your document in [Word format](https://quarto.org/docs/output-formats/ms-word.html) and email it to me.
